// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_QQpy2huApKYbKpIzKUImBf67WzNzo_g',
    appId: '1:134120535416:web:9202e62e1a563cbb7a848d',
    messagingSenderId: '134120535416',
    projectId: 'timefusion-a336e',
    authDomain: 'timefusion-a336e.firebaseapp.com',
    storageBucket: 'timefusion-a336e.appspot.com',
    measurementId: 'G-KE9KPGGNFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtQokXv4E3ojfFhGV0md8bNhlqN5cEtj8',
    appId: '1:134120535416:android:03efc75169e266d77a848d',
    messagingSenderId: '134120535416',
    projectId: 'timefusion-a336e',
    storageBucket: 'timefusion-a336e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxobQQyv68ce4JTELByEmFNNFrE3mocSA',
    appId: '1:134120535416:ios:bc256ec9e624c2d07a848d',
    messagingSenderId: '134120535416',
    projectId: 'timefusion-a336e',
    storageBucket: 'timefusion-a336e.appspot.com',
    iosClientId: '134120535416-s9cq264jjhmp92mjnbp4t1n0kcv5tr3d.apps.googleusercontent.com',
    iosBundleId: 'com.saransh.timesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxobQQyv68ce4JTELByEmFNNFrE3mocSA',
    appId: '1:134120535416:ios:7a889bde8c6f8cf17a848d',
    messagingSenderId: '134120535416',
    projectId: 'timefusion-a336e',
    storageBucket: 'timefusion-a336e.appspot.com',
    iosClientId: '134120535416-sv8b6u6uql0a1qjcg75ickdo8arp191h.apps.googleusercontent.com',
    iosBundleId: 'com.saransh.timesync.RunnerTests',
  );
}
